FROM node:22

WORKDIR /app

COPY . .

# Enable Corepack and set pnpm to version 8.15.0
RUN corepack enable && corepack prepare pnpm@8.15.0 --activate

# Install dependencies using the existing lockfile
RUN pnpm install --frozen-lockfile

# Build the app
RUN pnpm run build

# Run Prisma seed (make sure your .env is configured correctly)
RUN pnpm run db seed

EXPOSE 3000

CMD ["pnpm", "run", "start"]