        CREATE TABLE IF NOT EXISTS RecruitmentApplicant (
            id CHAR(36) NOT NULL PRIMARY KEY,
            candidateName VARCHAR(255) NOT NULL,
            profile TEXT,
            contactDate DATETIME,
            interviewDate DATETIME,
            contactType VARCHAR(50) NOT NULL,
            description TEXT,
            cvPath VARCHAR(500),
            potential BOOLEAN NOT NULL DEFAULT 0,
            retained BOOLEAN NOT NULL DEFAULT 0,
            createdAt DATETIME NOT NULL,
            createdBy CHAR(36) NOT NULL,
            updatedAt DATETIME,
            deleted BOOLEAN NOT NULL DEFAULT 0,
            deletedAt DATETIME NULL,
            deletedBy CHAR(36) NULL,
        INDEX createdBy (createdBy),
        INDEX deletedBy (deletedBy),

        CONSTRAINT RecruitmentApplicant_ibfk_1
        FOREIGN KEY (createdBy) REFERENCES Employee(id) ON DELETE RESTRICT,
        CONSTRAINT RecruitmentApplicant_ibfk_2
        FOREIGN KEY (deletedBy) REFERENCES Employee(id) ON DELETE SET NULL
        ) ENGINE = InnoDB;

        CREATE TABLE IF NOT EXISTS RecruitmentVacancy (
            id CHAR(36) NOT NULL PRIMARY KEY,
            title VARCHAR(255) NOT NULL,
            description TEXT,
            department VARCHAR(100) NOT NULL,
            contractType VARCHAR(50) NOT NULL,
            workRegime VARCHAR(50) NOT NULL,
            salaryMin DECIMAL(10,2),
            salaryMax DECIMAL(10,2),
            publishWebsite BOOLEAN DEFAULT 0  NOT NULL,
            publishVdab BOOLEAN DEFAULT 0 NOT NULL,
            publishOther BOOLEAN DEFAULT 0 NOT NULL,
            publishLinkedIn BOOLEAN DEFAULT 0 NOT NULL,
            publishTempAgencies BOOLEAN DEFAULT 0 NOT NULL,
            publishRecruitmentAgencies BOOLEAN DEFAULT 0 NOT NULL,
            otherPublication VARCHAR(255),
            createdAt DATETIME NOT NULL,
            updatedAt DATETIME NULL,
            createdBy CHAR(36) NOT NULL,
            deleted BOOLEAN DEFAULT 0 NOT NULL,
            deletedAt DATETIME NULL,
            deletedBy CHAR(36) NULL,

        INDEX createdBy (createdBy),
        INDEX deletedBy (deletedBy),

        CONSTRAINT RecruitmentVacancy_ibfk_1
        FOREIGN KEY (createdBy) REFERENCES Employee(id) ON DELETE RESTRICT,
        CONSTRAINT RecruitmentVacancy_ibfk_2
        FOREIGN KEY (deletedBy) REFERENCES Employee(id) ON DELETE SET NULL
        ) ENGINE = InnoDB;

            CREATE TABLE IF NOT EXISTS HrCertificationTraining (
        id CHAR(36) NOT NULL PRIMARY KEY,
        employeeId CHAR(36) NOT NULL,
        trainingName VARCHAR(255) NOT NULL,
        trainingType VARCHAR(30) NOT NULL,
        recurrenceInterval VARCHAR(10) NOT NULL DEFAULT 'none',
        trainingDocumentNumber VARCHAR(100) NULL,
        trainingDate DATETIME NOT NULL,
        certificateValidUntil DATETIME NULL,
        providerName VARCHAR(255) NOT NULL,
        includeInHseFile BOOLEAN NOT NULL DEFAULT 0,
        additionalInfo TEXT NULL,
        createdAt DATETIME NOT NULL,
        createdBy CHAR(36) NOT NULL,
        updatedAt DATETIME NULL,
        updatedBy CHAR(36) NULL,
        deleted BOOLEAN NOT NULL DEFAULT 0,
        deletedAt DATETIME NULL,
        deletedBy CHAR(36) NULL,
        INDEX employeeId (employeeId),
        INDEX createdBy (createdBy),
        INDEX deletedBy (deletedBy),
        trainingDocumentNumber VARCHAR(100) NULL,
        includeInHseFile BOOLEAN NOT NULL DEFAULT 0,
        CONSTRAINT HrCertificationTraining_ibfk_1 FOREIGN KEY (employeeId) REFERENCES Employee(id) ON UPDATE RESTRICT,
        CONSTRAINT HrCertificationTraining_ibfk_2 FOREIGN KEY (createdBy) REFERENCES Employee(id) ON UPDATE RESTRICT,
        CONSTRAINT HrCertificationTraining_ibfk_3 FOREIGN KEY (deletedBy) REFERENCES Employee(id) ON UPDATE RESTRICT,
        CONSTRAINT HrCertificationTraining_ibfk_4 FOREIGN KEY (updatedBy) REFERENCES Employee(id) ON UPDATE RESTRICT
        ) ENGINE = InnoDB;

    CREATE TABLE IF NOT EXISTS HrEmployeeAbsence (
        id CHAR(36) NOT NULL PRIMARY KEY,
        employeeId CHAR(36) NOT NULL,
        year INT NOT NULL,
        absenceType VARCHAR(30) NOT NULL,
        days DECIMAL(6,2) NOT NULL DEFAULT 0,
        additionalInfo TEXT NULL,
        createdAt DATETIME NOT NULL,
        createdBy CHAR(36) NOT NULL,
        updatedAt DATETIME NULL,
        updatedBy CHAR(36) NULL,
        deleted BOOLEAN NOT NULL DEFAULT 0,
        deletedAt DATETIME NULL,
        deletedBy CHAR(36) NULL,

        INDEX employeeId (employeeId),
        INDEX year (year),
        INDEX absenceType (absenceType),

        CONSTRAINT HrEmployeeAbsence_ibfk_1 FOREIGN KEY (employeeId) REFERENCES Employee(id) ON UPDATE RESTRICT,
        CONSTRAINT HrEmployeeAbsence_ibfk_2 FOREIGN KEY (createdBy) REFERENCES Employee(id) ON UPDATE RESTRICT,
        CONSTRAINT HrEmployeeAbsence_ibfk_3 FOREIGN KEY (deletedBy) REFERENCES Employee(id) ON UPDATE RESTRICT,
        CONSTRAINT HrEmployeeAbsence_ibfk_4 FOREIGN KEY (updatedBy) REFERENCES Employee(id) ON UPDATE RESTRICT
        );

    CREATE TABLE IF NOT EXISTS HrEmployeeHseFile (
        id CHAR(36) NOT NULL PRIMARY KEY,
        employeeId CHAR(36) NOT NULL,
        includeEmployeeData BOOLEAN NOT NULL DEFAULT 1,
        includePartnerData BOOLEAN NOT NULL DEFAULT 0,
        partnerName VARCHAR(255) NULL,
        partnerPhone VARCHAR(100) NULL,
        partnerEmail VARCHAR(255) NULL,
        includeEmergencyContact BOOLEAN NOT NULL DEFAULT 1,
        includeEmployerData BOOLEAN NOT NULL DEFAULT 1,
        employerCompanyId CHAR(36) NULL,
        employerName VARCHAR(255) NULL,
        employerContactName VARCHAR(255) NULL,
        employerPhone VARCHAR(100) NULL,
        employerEmail VARCHAR(255) NULL,
        includeMedicalExamination BOOLEAN NOT NULL DEFAULT 1,
        lastMedicalExaminationDate DATETIME NULL,
        lastMedicalExaminationValidUntil DATETIME NULL,
        lastMedicalExaminationProvider VARCHAR(255) NULL,
        includeTrainingData BOOLEAN NOT NULL DEFAULT 1,
        createdAt DATETIME NOT NULL,
        createdBy CHAR(36) NOT NULL,
        updatedAt DATETIME NULL,
        updatedBy CHAR(36) NULL,
        deleted BOOLEAN NOT NULL DEFAULT 0,
        deletedAt DATETIME NULL,
        deletedBy CHAR(36) NULL,

        UNIQUE KEY employeeId (employeeId),
        INDEX employerCompanyId (employerCompanyId),
        INDEX createdBy (createdBy),
        INDEX updatedBy (updatedBy),
        INDEX deletedBy (deletedBy),

        CONSTRAINT HrEmployeeHseFile_ibfk_1 FOREIGN KEY (employeeId) REFERENCES Employee(id) ON UPDATE RESTRICT,
        CONSTRAINT HrEmployeeHseFile_ibfk_2 FOREIGN KEY (employerCompanyId) REFERENCES Company(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT HrEmployeeHseFile_ibfk_3 FOREIGN KEY (createdBy) REFERENCES Employee(id) ON UPDATE RESTRICT,
        CONSTRAINT HrEmployeeHseFile_ibfk_4 FOREIGN KEY (updatedBy) REFERENCES Employee(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT HrEmployeeHseFile_ibfk_5 FOREIGN KEY (deletedBy) REFERENCES Employee(id) ON DELETE RESTRICT ON UPDATE RESTRICT
        ) ENGINE = InnoDB;

    CREATE TABLE IF NOT EXISTS HrEmployeeOvertime (
        id CHAR(36) NOT NULL PRIMARY KEY,
        employeeId CHAR(36) NOT NULL,
        projectId CHAR(36) NOT NULL,
        sourceTimeRegistryId CHAR(36) NULL,
        overtimeDate DATETIME NOT NULL,
        hours DECIMAL(7,2) NOT NULL,
        description TEXT NULL,
        createdAt DATETIME NOT NULL,
        createdBy CHAR(36) NOT NULL,
        updatedAt DATETIME NULL,
        updatedBy CHAR(36) NULL,
        deleted BOOLEAN NOT NULL DEFAULT 0,
        deletedAt DATETIME NULL,
        deletedBy CHAR(36) NULL,

        INDEX employeeId (employeeId),
        INDEX projectId (projectId),
        INDEX sourceTimeRegistryId (sourceTimeRegistryId),
        INDEX overtimeDate (overtimeDate),
        INDEX createdBy (createdBy),
        INDEX updatedBy (updatedBy),
        INDEX deletedBy (deletedBy),

        CONSTRAINT HrEmployeeOvertime_ibfk_1 FOREIGN KEY (employeeId) REFERENCES Employee(id) ON UPDATE RESTRICT,
        CONSTRAINT HrEmployeeOvertime_ibfk_2 FOREIGN KEY (projectId) REFERENCES Project(id) ON UPDATE RESTRICT,
        CONSTRAINT HrEmployeeOvertime_ibfk_3 FOREIGN KEY (sourceTimeRegistryId) REFERENCES TimeRegistry(id) ON DELETE SET NULL ON UPDATE RESTRICT,
        CONSTRAINT HrEmployeeOvertime_ibfk_4 FOREIGN KEY (createdBy) REFERENCES Employee(id) ON UPDATE RESTRICT,
        CONSTRAINT HrEmployeeOvertime_ibfk_5 FOREIGN KEY (updatedBy) REFERENCES Employee(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT HrEmployeeOvertime_ibfk_6 FOREIGN KEY (deletedBy) REFERENCES Employee(id) ON DELETE RESTRICT ON UPDATE RESTRICT
        ) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS HrFacilityVehicle (
        id CHAR(36) NOT NULL PRIMARY KEY,
        serialTrackedId CHAR(36) NULL,
        assignedEmployeeId CHAR(36) NULL,
        licensePlate VARCHAR(50) NULL,
        brand VARCHAR(100) NULL,
        model VARCHAR(100) NULL,
        vin VARCHAR(100) NULL,
        status VARCHAR(30) NOT NULL DEFAULT 'active',
        conditionStatus VARCHAR(100) NULL,
        signedVehicleDocument BOOLEAN NOT NULL DEFAULT 0,
        signedDocumentFileId VARCHAR(255) NULL,
        monthlyFuelBudget DECIMAL(10,2) NULL,
        notes TEXT NULL,
        createdAt DATETIME NOT NULL,
        createdBy CHAR(36) NOT NULL,
        updatedAt DATETIME NULL,
        updatedBy CHAR(36) NULL,
        deleted BOOLEAN NOT NULL DEFAULT 0,
        deletedAt DATETIME NULL,
        deletedBy CHAR(36) NULL,

        UNIQUE KEY licensePlate (licensePlate),
        INDEX serialTrackedId (serialTrackedId),
        INDEX assignedEmployeeId (assignedEmployeeId),
        INDEX status (status),
        INDEX createdBy (createdBy),
        INDEX updatedBy (updatedBy),
        INDEX deletedBy (deletedBy),

        CONSTRAINT HrFacilityVehicle_ibfk_1 FOREIGN KEY (serialTrackedId) REFERENCES MaterialSerialTrack(id) ON DELETE SET NULL ON UPDATE RESTRICT,
        CONSTRAINT HrFacilityVehicle_ibfk_2 FOREIGN KEY (assignedEmployeeId) REFERENCES Employee(id) ON DELETE SET NULL ON UPDATE RESTRICT,
        CONSTRAINT HrFacilityVehicle_ibfk_3 FOREIGN KEY (createdBy) REFERENCES Employee(id) ON UPDATE RESTRICT,
        CONSTRAINT HrFacilityVehicle_ibfk_4 FOREIGN KEY (updatedBy) REFERENCES Employee(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT HrFacilityVehicle_ibfk_5 FOREIGN KEY (deletedBy) REFERENCES Employee(id) ON DELETE RESTRICT ON UPDATE RESTRICT
        ) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS HrFacilityFuelCard (
        id CHAR(36) NOT NULL PRIMARY KEY,
        vehicleId CHAR(36) NULL,
        employeeId CHAR(36) NULL,
        cardNumber VARCHAR(100) NOT NULL,
        provider VARCHAR(100) NULL,
        monthlyBudget DECIMAL(10,2) NULL,
        currentMonthSpend DECIMAL(10,2) NOT NULL DEFAULT 0.00,
        active BOOLEAN NOT NULL DEFAULT 1,
        notes TEXT NULL,
        createdAt DATETIME NOT NULL,
        createdBy CHAR(36) NOT NULL,
        updatedAt DATETIME NULL,
        updatedBy CHAR(36) NULL,
        deleted BOOLEAN NOT NULL DEFAULT 0,
        deletedAt DATETIME NULL,
        deletedBy CHAR(36) NULL,

        UNIQUE KEY cardNumber (cardNumber),
        INDEX vehicleId (vehicleId),
        INDEX employeeId (employeeId),
        INDEX active (active),
        INDEX createdBy (createdBy),
        INDEX updatedBy (updatedBy),
        INDEX deletedBy (deletedBy),

        CONSTRAINT HrFacilityFuelCard_ibfk_1 FOREIGN KEY (vehicleId) REFERENCES HrFacilityVehicle(id) ON DELETE SET NULL ON UPDATE RESTRICT,
        CONSTRAINT HrFacilityFuelCard_ibfk_2 FOREIGN KEY (employeeId) REFERENCES Employee(id) ON DELETE SET NULL ON UPDATE RESTRICT,
        CONSTRAINT HrFacilityFuelCard_ibfk_3 FOREIGN KEY (createdBy) REFERENCES Employee(id) ON UPDATE RESTRICT,
        CONSTRAINT HrFacilityFuelCard_ibfk_4 FOREIGN KEY (updatedBy) REFERENCES Employee(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT HrFacilityFuelCard_ibfk_5 FOREIGN KEY (deletedBy) REFERENCES Employee(id) ON DELETE RESTRICT ON UPDATE RESTRICT
        ) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS HrFacilityFine (
        id CHAR(36) NOT NULL PRIMARY KEY,
        vehicleId CHAR(36) NULL,
        employeeId CHAR(36) NULL,
        fineDate DATETIME NOT NULL,
        amount DECIMAL(10,2) NOT NULL,
        referenceNumber VARCHAR(100) NULL,
        description TEXT NULL,
        paidByEmployee BOOLEAN NOT NULL DEFAULT 0,
        paidAt DATETIME NULL,
        createdAt DATETIME NOT NULL,
        createdBy CHAR(36) NOT NULL,
        updatedAt DATETIME NULL,
        updatedBy CHAR(36) NULL,
        deleted BOOLEAN NOT NULL DEFAULT 0,
        deletedAt DATETIME NULL,
        deletedBy CHAR(36) NULL,

        INDEX vehicleId (vehicleId),
        INDEX employeeId (employeeId),
        INDEX fineDate (fineDate),
        INDEX paidByEmployee (paidByEmployee),
        INDEX createdBy (createdBy),
        INDEX updatedBy (updatedBy),
        INDEX deletedBy (deletedBy),

        CONSTRAINT HrFacilityFine_ibfk_1 FOREIGN KEY (vehicleId) REFERENCES HrFacilityVehicle(id) ON DELETE SET NULL ON UPDATE RESTRICT,
        CONSTRAINT HrFacilityFine_ibfk_2 FOREIGN KEY (employeeId) REFERENCES Employee(id) ON DELETE SET NULL ON UPDATE RESTRICT,
        CONSTRAINT HrFacilityFine_ibfk_3 FOREIGN KEY (createdBy) REFERENCES Employee(id) ON UPDATE RESTRICT,
        CONSTRAINT HrFacilityFine_ibfk_4 FOREIGN KEY (updatedBy) REFERENCES Employee(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT HrFacilityFine_ibfk_5 FOREIGN KEY (deletedBy) REFERENCES Employee(id) ON DELETE RESTRICT ON UPDATE RESTRICT
        ) ENGINE = InnoDB;
