FROM mariadb:11

ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
ENV MYSQL_DATABASE=${MYSQL_DATABASE}
ENV MYSQL_USER=${MYSQL_USER}
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}

COPY init.sql /docker-entrypoint-initdb.d/
COPY alter.sql /migrations/alter.sql
COPY docker-entrypoint-custom.sh /usr/local/bin/docker-entrypoint-custom.sh

RUN chmod +x /usr/local/bin/docker-entrypoint-custom.sh

ENTRYPOINT ["docker-entrypoint-custom.sh"]